---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "tirlearner"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::tir-learner=3.0.3"
